package jetbrains.mps.lang.resources.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.BehaviorRegistry;
import jetbrains.mps.smodel.language.ConceptRegistry;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.SModifiersImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.util.IconCreationUtil;
import org.jetbrains.mps.openapi.util.Consumer;
import java.awt.Font;
import java.awt.Color;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.awt.font.TextLayout;
import java.awt.geom.Rectangle2D;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;

public final class TextCustomizable__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, "jetbrains.mps.lang.resources.structure.TextCustomizable");
  private static final BehaviorRegistry REGISTRY = ConceptRegistry.getInstance().getBehaviorRegistry();

  public static final SMethod<byte[]> getImageForGeneration_id2p1v3tObywX = new SMethodBuilder<byte[]>(new SJavaCompoundTypeImpl(byte[].class)).name("getImageForGeneration").modifiers(SModifiersImpl.create(8, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("2p1v3tObywX").registry(REGISTRY).build();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getImageForGeneration_id2p1v3tObywX);

  private static void ___init___(@NotNull SNode __thisNode__) {
    SPropertyOperations.set(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380727426L, "fontSize"), "" + (10));
    SPropertyOperations.set(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x35b02a7f3bec7ed8L, "xOffset"), "0.0");
    SPropertyOperations.set(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x35b02a7f3bec7eddL, "yOffset"), "0.0");
  }

  /*package*/ static byte[] getImageForGeneration_id2p1v3tObywX(@NotNull final SNode __thisNode__) {
    return IconCreationUtil.drawIcon(new Consumer<IconCreationUtil.DrawContext>() {
      public void consume(IconCreationUtil.DrawContext dc) {

        int fontStyle;
        if (SPropertyOperations.hasValue(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380755ad6L, "fontStyle"), "Plain", "Plain")) {
          fontStyle = Font.PLAIN;
        } else if (SPropertyOperations.hasValue(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380755ad6L, "fontStyle"), "Italic", "Plain")) {
          fontStyle = Font.ITALIC;
        } else if (SPropertyOperations.hasValue(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380755ad6L, "fontStyle"), "Bold", "Plain")) {
          fontStyle = Font.BOLD;
        } else {
          throw new RuntimeException("invalid font style: " + SPropertyOperations.getString_def(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380755ad6L, "fontStyle"), "Plain"));
        }

        String fontFace;
        if (SPropertyOperations.hasValue(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380738fabL, "fontFamily"), "Dialog", "Dialog")) {
          fontFace = Font.DIALOG;
        } else if (SPropertyOperations.hasValue(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380738fabL, "fontFamily"), "DialogInput", "Dialog")) {
          fontFace = Font.DIALOG_INPUT;
        } else if (SPropertyOperations.hasValue(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380738fabL, "fontFamily"), "SansSerif", "Dialog")) {
          fontFace = Font.SANS_SERIF;
        } else if (SPropertyOperations.hasValue(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380738fabL, "fontFamily"), "Serif", "Dialog")) {
          fontFace = Font.SERIF;
        } else if (SPropertyOperations.hasValue(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380738fabL, "fontFamily"), "Monospaced", "Dialog")) {
          fontFace = Font.MONOSPACED;
        } else {
          throw new RuntimeException("invalid font face " + SPropertyOperations.getString_def(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380738fabL, "fontFamily"), "Dialog"));
        }

        Font font = new Font(fontFace, fontStyle, SPropertyOperations.getInteger(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x452c726380727426L, "fontSize")));

        dc.g.setColor(new Color((int) Color__BehaviorDescriptor.getIntValue_id1BguvjG4ybo.invoke(SLinkOperations.getTarget(__thisNode__, MetaAdapterFactory.getContainmentLink(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x26417c37742e28b9L, 0x19d079f4ec114c16L, "color")))));
        dc.g.setFont(font);

        TextLayout text = new TextLayout(SPropertyOperations.getString(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x26417c37742e28b9L, 0x26417c37742e28beL, "text")), font, dc.g.getFontRenderContext());
        Rectangle2D rect = text.getBounds();

        text.draw(dc.g, ((float) (((float) dc.width) / 2 - rect.getCenterX() + Float.parseFloat(SPropertyOperations.getString(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x35b02a7f3bec7ed8L, "xOffset"))))), ((float) (((float) dc.height) / 2 - rect.getCenterY() + Float.parseFloat(SPropertyOperations.getString(__thisNode__, MetaAdapterFactory.getProperty(0x982eb8df2c964bd7L, 0x996311712ea622e5L, 0x452c726380727365L, 0x35b02a7f3bec7eddL, "yOffset"))))));
      }
    });
  }

  /*package*/ TextCustomizable__BehaviorDescriptor() {
    super(REGISTRY);
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((byte[]) getImageForGeneration_id2p1v3tObywX(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }
}
