package jetbrains.mps.lang.editor.ide.intentions.test;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseEditorTestBody;
import junit.framework.Assert;

@MPSLaunch
public class MigrateToIndent_NoLayout_Test extends BaseTransformationTest {
  @Test
  public void test_MigrateToIndent_NoLayout() throws Throwable {
    initTest("${mps_home}", "r:ac7fc8d2-009b-4709-96f8-5178c2bb268c(jetbrains.mps.lang.editor.ide.intentions.test)");
    runTest("jetbrains.mps.lang.editor.ide.intentions.test.MigrateToIndent_NoLayout_Test$TestBody", "testMethod", false);
  }

  @MPSLaunch
  public static class TestBody extends BaseEditorTestBody {
    @Override
    public void testMethodImpl() throws Exception {
      initEditorComponent("2390303184246514707", "2390303184246645057");
      Assert.assertTrue(isIntentionApplicable("jetbrains.mps.lang.editor.intentions.MigrateToIndentLayout_Intention", myStart.getNode()));
      invokeIntention("jetbrains.mps.lang.editor.intentions.MigrateToIndentLayout_Intention", myStart.getNode());
    }
  }
}
