package jetbrains.mps.lang.resources.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EFontFamily {
  Dialog("Dialog", "Dialog"),
  DialogInput("DialogInput", "DialogInput"),
  SansSerif("SansSerif", "SansSerif"),
  Serif("Serif", "Serif"),
  Monospaced("Monospaced", "Monospaced");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private EFontFamily(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<EFontFamily> getConstants() {
    List<EFontFamily> list = ListSequence.fromList(new LinkedList<EFontFamily>());
    ListSequence.fromList(list).addElement(EFontFamily.Dialog);
    ListSequence.fromList(list).addElement(EFontFamily.DialogInput);
    ListSequence.fromList(list).addElement(EFontFamily.SansSerif);
    ListSequence.fromList(list).addElement(EFontFamily.Serif);
    ListSequence.fromList(list).addElement(EFontFamily.Monospaced);
    return list;
  }
  public static EFontFamily getDefault() {
    return EFontFamily.Dialog;
  }
  public static EFontFamily parseValue(String value) {
    if (value == null) {
      return EFontFamily.getDefault();
    }
    if (value.equals(EFontFamily.Dialog.getValueAsString())) {
      return EFontFamily.Dialog;
    }
    if (value.equals(EFontFamily.DialogInput.getValueAsString())) {
      return EFontFamily.DialogInput;
    }
    if (value.equals(EFontFamily.SansSerif.getValueAsString())) {
      return EFontFamily.SansSerif;
    }
    if (value.equals(EFontFamily.Serif.getValueAsString())) {
      return EFontFamily.Serif;
    }
    if (value.equals(EFontFamily.Monospaced.getValueAsString())) {
      return EFontFamily.Monospaced;
    }
    return EFontFamily.getDefault();
  }
}
