package jetbrains.mps.lang.resources.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.PropertySupport;
import java.util.Iterator;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class EFontStyle_PropertySupport extends PropertySupport {
  public boolean canSetValue(String value) {
    if (value == null) {
      return true;
    }
    Iterator<EFontStyle> constants = ListSequence.fromList(EFontStyle.getConstants()).iterator();
    while (constants.hasNext()) {
      EFontStyle constant = constants.next();
      if (value.equals(constant.getName())) {
        return true;
      }
    }
    return false;
  }
  public String toInternalValue(String value) {
    if (value == null) {
      return null;
    }
    Iterator<EFontStyle> constants = ListSequence.fromList(EFontStyle.getConstants()).iterator();
    while (constants.hasNext()) {
      EFontStyle constant = constants.next();
      if (value.equals(constant.getName())) {
        return constant.getValueAsString();
      }
    }
    return null;
  }
  public String fromInternalValue(String value) {
    EFontStyle constant = EFontStyle.parseValue(value);
    if (constant != null) {
      return constant.getName();
    }
    return "";
  }
}
