package jetbrains.mps.lang.resources.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum EFontStyle {
  Plain("Plain", "Plain"),
  Bold("Bold", "Bold"),
  Italic("Italic", "Italic");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private EFontStyle(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<EFontStyle> getConstants() {
    List<EFontStyle> list = ListSequence.fromList(new LinkedList<EFontStyle>());
    ListSequence.fromList(list).addElement(EFontStyle.Plain);
    ListSequence.fromList(list).addElement(EFontStyle.Bold);
    ListSequence.fromList(list).addElement(EFontStyle.Italic);
    return list;
  }
  public static EFontStyle getDefault() {
    return EFontStyle.Plain;
  }
  public static EFontStyle parseValue(String value) {
    if (value == null) {
      return EFontStyle.getDefault();
    }
    if (value.equals(EFontStyle.Plain.getValueAsString())) {
      return EFontStyle.Plain;
    }
    if (value.equals(EFontStyle.Bold.getValueAsString())) {
      return EFontStyle.Bold;
    }
    if (value.equals(EFontStyle.Italic.getValueAsString())) {
      return EFontStyle.Italic;
    }
    return EFontStyle.getDefault();
  }
}
