package jetbrains.mps.lang.resources.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a3a0a21b0w = new IconResource("iconResourceBundle.png", IconContainer.class);
}
