package jetbrains.mps.lang.quotation.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.quotation.behavior.NodeBuilderNode__BehaviorDescriptor;

public class NodeBuilder_DataFlow extends DataFlowBuilder {
  public void build(final DataFlowBuilderContext _context) {
    SNode quotedNode = SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x3a13115c633c4c5cL, 0xbbcc75c4219e9555L, 0x4bb51009d20a4a9dL, 0x4bb51009d20a4a9eL, "quotedNode"));
    if (quotedNode != null) {
      for (SNode expr : NodeBuilderNode__BehaviorDescriptor.getExternalExpressions_idRRzwLnBxZy.invoke(quotedNode)) {
        _context.getBuilder().build((SNode) expr);
      }
    }
  }
}
