package jetbrains.mps.lang.test.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a2a0a81b0bd = new IconResource("nodesTest.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a3a0a33b0bd = new IconResource("nodesTest.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a75b0bd = new IconResource("nodesTest.png", IconContainer.class);
}
